name: secure_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  assets: ^0.0.1
  awesome_bottom_bar: ^1.2.4
  bloc: ^8.1.3
  buttons_tabbar: ^1.3.8
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: 2.24.2
  firebase_storage: ^11.6.0
  floating_bottom_bar: ^0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  gap: ^3.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  lottie: ^2.7.0
  provider: ^6.1.2
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2
  svg_flutter: ^0.0.1
  uuid: ^4.2.2
  fluttertoast: ^8.2.5

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/certificate.crt
    